/* Stage 10.1.5 — permanent registration QR + PIN auth concept */
const AMP_AUTH_KEY='ampclub.auth.v1';
const AMP_TEST_REGISTER_URL=location.origin+location.pathname+'?register=1';
const AMP_FINAL_REGISTER_URL='https://amplituda-nn.ru/club';
let ampAuth=(()=>{try{return JSON.parse(localStorage.getItem(AMP_AUTH_KEY))||{registered:false,phone:'',pin:'',signedIn:false,recovery:['telegram','max']}}catch(e){return {registered:false,phone:'',pin:'',signedIn:false,recovery:['telegram','max']}}})();
let ampRegStep=1,ampRegPhone='',ampRecoveryStep=1,ampRecoveryChannel='telegram';
const ampSaveAuth=()=>localStorage.setItem(AMP_AUTH_KEY,JSON.stringify(ampAuth));
const ampDigits=v=>String(v||'').replace(/\D/g,'');
const ampTenPhone=v=>{let d=ampDigits(v);if(d.length===11&&(d[0]==='7'||d[0]==='8'))d=d.slice(1);return d};
const ampRegistrationQr=()=>`https://quickchart.io/qr?size=260&margin=1&text=${encodeURIComponent(AMP_TEST_REGISTER_URL)}`;
function ampAuthShell(inner){return `<main class="auth-shell"><section class="auth-card card"><div class="auth-brand"><div class="logo"><img src="./amp-logo.svg?v=10.1.5" alt="Амплитуда"></div><div><h1>АМ Клуб</h1><p>Амплитуда</p></div></div>${inner}</section></main>`}
function ampRegistrationPage(){let body='';if(ampRegStep===1)body=`<h2>Регистрация</h2><p>Введите номер телефона. В боевой версии подтверждение номера отправляется один раз при первой регистрации.</p><label class="field"><span>Телефон</span><input id="regPhone" inputmode="tel" autocomplete="tel" placeholder="9991234567" value="${esc(ampRegPhone)}"></label><button class="btn primary wide" data-auth="send-register-code">Продолжить</button><div class="auth-note">Тестовый код подтверждения: <b>1111</b></div>`;
if(ampRegStep===2)body=`<h2>Подтвердите телефон</h2><p>Код отправлен на номер ${esc(ampRegPhone)}. Это единственная обязательная проверка телефона при регистрации.</p><label class="field"><span>Код</span><input id="regCode" inputmode="numeric" maxlength="4" placeholder="1111"></label><button class="btn primary wide" data-auth="verify-register-code">Подтвердить</button><button class="btn ghost wide" data-auth="back-register">Назад</button><div class="auth-note">В тесте используйте <b>1111</b>.</div>`;
if(ampRegStep===3)body=`<h2>Создайте PIN</h2><p>Четыре цифры. В дальнейшем SMS для обычного входа не понадобится.</p><label class="field"><span>PIN</span><input id="regPin" type="password" inputmode="numeric" maxlength="4" autocomplete="new-password" placeholder="••••"></label><label class="field"><span>Повторите PIN</span><input id="regPin2" type="password" inputmode="numeric" maxlength="4" autocomplete="new-password" placeholder="••••"></label><button class="btn primary wide" data-auth="save-pin">Сохранить PIN</button>`;
if(ampRegStep===4)body=`<div class="auth-success">✓</div><h2>Регистрация завершена</h2><p>Телефон привязан. Для последующих входов используйте номер телефона и PIN. На своём телефоне приложение будет сохранять авторизацию.</p><a class="btn primary wide auth-link" href="${location.pathname}">Открыть АМ Клуб</a><div class="auth-note">Если PIN забыт — восстановление через Telegram или MAX; SMS остаётся резервным каналом.</div>`;return ampAuthShell(body)}
function ampLoginPage(){return ampAuthShell(`<h2>Вход</h2><p>SMS на каждый вход не нужен. Введите телефон и ваш 4-значный PIN.</p><label class="field"><span>Телефон</span><input id="loginPhone" inputmode="tel" autocomplete="tel" value="${esc(ampAuth.phone||'9991234567')}"></label><label class="field"><span>PIN</span><input id="loginPin" type="password" inputmode="numeric" maxlength="4" autocomplete="current-password" placeholder="••••"></label><button class="btn primary wide" data-auth="login-pin">Войти</button><button class="btn ghost wide" data-auth="forgot-pin">Забыли PIN?</button><a class="text-link" href="?register=1">Регистрация</a>`)}
function ampRecoveryPage(){const channel=ampRecoveryChannel==='max'?'MAX':'Telegram';let body='';if(ampRecoveryStep===1)body=`<h2>Восстановление PIN</h2><p>Выберите привязанный канал. Код восстановления отправляем туда бесплатно; SMS используем только как запасной вариант.</p><div class="recovery-buttons"><button class="btn secondary" data-auth="recovery-channel" data-channel="telegram">Telegram</button><button class="btn secondary" data-auth="recovery-channel" data-channel="max">MAX</button><button class="btn ghost" data-auth="recovery-channel" data-channel="sms">SMS — резерв</button></div><button class="btn ghost wide" data-auth="back-login">Назад</button>`;
if(ampRecoveryStep===2)body=`<h2>Код отправлен</h2><p>Тестовый код восстановления отправлен через ${esc(channel)}.</p><label class="field"><span>Код</span><input id="recoveryCode" inputmode="numeric" maxlength="4" placeholder="2222"></label><button class="btn primary wide" data-auth="verify-recovery">Продолжить</button><div class="auth-note">В тесте код: <b>2222</b>.</div>`;
if(ampRecoveryStep===3)body=`<h2>Новый PIN</h2><label class="field"><span>Новый PIN</span><input id="recoveryPin" type="password" inputmode="numeric" maxlength="4" placeholder="••••"></label><label class="field"><span>Повторите PIN</span><input id="recoveryPin2" type="password" inputmode="numeric" maxlength="4" placeholder="••••"></label><button class="btn primary wide" data-auth="save-recovery-pin">Сохранить</button>`;return ampAuthShell(body)}
let ampAuthScreen='';
const ampPreviousProfile=profile;
profile=function(){let html=ampPreviousProfile();html=html.replace(/<section class="login-card card">[\s\S]*?<\/section>/,`<section class="security-card card"><div><h3>Вход в приложение</h3><p>После первой регистрации — телефон + 4-значный PIN. На этом устройстве вход сохраняется.</p></div><a class="btn secondary auth-link" href="?login=1">Проверить вход</a></section>`);return html};
const ampPreviousAdminChannels=adminChannels;
adminChannels=function(){const qr=ampRegistrationQr();return ampPreviousAdminChannels()+`<section class="registration-admin card"><div class="registration-copy"><h2>Постоянный QR регистрации</h2><p>В тесте QR ведёт на текущую страницу регистрации. Для печати используем постоянный адрес <b>${AMP_FINAL_REGISTER_URL}</b>. После переноса приложения этот адрес не меняется.</p><a class="btn secondary auth-link" href="?register=1" target="_blank">Открыть тест регистрации ↗</a></div><img src="${qr}" alt="QR регистрации АМ Клуба"></section>`};
const ampPreviousRender=render;
render=function(){const q=new URLSearchParams(location.search);if(q.get('register')==='1'){document.getElementById('app').innerHTML=ampRegistrationPage();return}if(q.get('login')==='1'||ampAuthScreen==='login'){document.getElementById('app').innerHTML=ampLoginPage();return}if(ampAuthScreen==='recovery'){document.getElementById('app').innerHTML=ampRecoveryPage();return}ampPreviousRender()};
document.addEventListener('click',e=>{const b=e.target.closest('[data-auth]');if(!b)return;e.preventDefault();const a=b.dataset.auth;if(a==='send-register-code'){const p=ampTenPhone(document.querySelector('#regPhone')?.value);if(p.length!==10){toast('Введите 10 цифр телефона');return}ampRegPhone=p;ampRegStep=2;render()}else if(a==='back-register'){ampRegStep=1;render()}else if(a==='verify-register-code'){if(document.querySelector('#regCode')?.value!=='1111'){toast('Неверный тестовый код');return}ampRegStep=3;render()}else if(a==='save-pin'){const p=document.querySelector('#regPin')?.value||'',p2=document.querySelector('#regPin2')?.value||'';if(!/^\d{4}$/.test(p)){toast('PIN должен состоять из 4 цифр');return}if(p!==p2){toast('PIN не совпадает');return}ampAuth={...ampAuth,registered:true,phone:ampRegPhone,pin:p,signedIn:true};ampSaveAuth();ampRegStep=4;render()}else if(a==='login-pin'){const phone=ampTenPhone(document.querySelector('#loginPhone')?.value),pin=document.querySelector('#loginPin')?.value||'';if(!ampAuth.registered){toast('Сначала зарегистрируйтесь');return}if(phone!==ampTenPhone(ampAuth.phone)||pin!==ampAuth.pin){toast('Телефон или PIN неверны');return}ampAuth.signedIn=true;ampSaveAuth();location.href=location.pathname}else if(a==='forgot-pin'){ampAuthScreen='recovery';ampRecoveryStep=1;render()}else if(a==='back-login'){ampAuthScreen='login';render()}else if(a==='recovery-channel'){ampRecoveryChannel=b.dataset.channel;ampRecoveryStep=2;render()}else if(a==='verify-recovery'){if(document.querySelector('#recoveryCode')?.value!=='2222'){toast('Неверный тестовый код');return}ampRecoveryStep=3;render()}else if(a==='save-recovery-pin'){const p=document.querySelector('#recoveryPin')?.value||'',p2=document.querySelector('#recoveryPin2')?.value||'';if(!/^\d{4}$/.test(p)){toast('PIN должен состоять из 4 цифр');return}if(p!==p2){toast('PIN не совпадает');return}ampAuth.pin=p;ampAuth.signedIn=true;ampSaveAuth();ampAuthScreen='login';toast('PIN изменён');render()}});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
render();
