let state=(()=>{try{return JSON.parse(localStorage.getItem('ampclub.stage10.1'))||JSON.parse(JSON.stringify(seed))}catch(e){return JSON.parse(JSON.stringify(seed))}})();
let view='home', admin=false, adminTab='customers', selectedCustomer='c1', promoFilter='Все', modal=null, toastTimer;
const save=()=>localStorage.setItem('ampclub.stage10.1',JSON.stringify(state));
const current=()=>state.customers.find(x=>x.id===state.customer.id)||state.customer;
const birthdayToday=c=>c.birth&&c.birth.slice(5)===today.slice(5);
function eligibility(r,c=current()){
 const reasons=[]; if(!r.active) reasons.push('Позиция отключена'); if(r.stock<=0) reasons.push('Нет в наличии');
 if(c.balance<r.price) reasons.push('Недостаточно АМ'); if((r.minDiscount||0)>c.discount) reasons.push(`Нужна скидка от ${r.minDiscount}%`);
 if(r.gender&&r.gender!=='any'&&r.gender!==c.gender) reasons.push(r.gender==='male'?'Только для мужчин':'Только для женщин');
 if(r.birthday&&!birthdayToday(c)) reasons.push('Только в день рождения');
 if(r.from&&today<r.from) reasons.push('Период ещё не начался'); if(r.to&&today>r.to) reasons.push('Период завершён');
 const count=state.redemptions.filter(x=>x.reward===r.id&&x.customer===c.id&&x.status!=='Отменено').length; if(r.limit&&count>=r.limit) reasons.push('Лимит на клиента исчерпан');
 return reasons;
}
function head(title,sub,withAdmin=true){return `<header class="top"><div class="brand"><div class="logo">⚡</div><div><h1 class="title">${title}</h1><div class="sub">${sub||''}</div></div></div>${withAdmin?`<button class="admin-switch" data-action="toggle-admin">${admin?'Клиент':'Админка'}</button>`:''}</header>`}
const navItems=[['home','⌂','Главная'],['promotions','★','Акции'],['orders','▤','Заказы'],['history','↕','История'],['profile','●','Профиль']];
function nav(){return `<nav class="nav"><div class="navrail">${navItems.map(([id,ic,t])=>`<button data-view="${id}" class="${view===id?'active':''}"><b>${ic}</b>${t}</button>`).join('')}</div></nav>`}
function home(){const c=current(),pct=Math.min(100,Math.max(0,c.turnover/60000*100)); const list=state.rewards.filter(r=>r.active).sort((a,b)=>a.sort-b.sort).slice(0,6);return `${head('АМ Клуб','Амплитуда • участник клуба')}<section class="balance card"><div class="label">Мои АМ</div><div class="value">${c.balance}</div><div class="row"><span>Скидка ${c.discount}%</span><b>${c.name}</b></div></section><section class="progress-card card"><div class="progress-head"><span>До следующей скидки</span><span>${money(Math.max(0,60000-c.turnover))}</span></div><div class="progress"><i style="width:${pct}%"></i></div><div class="sub">Оборот ${money(c.turnover)} · следующая ступень 7%</div></section><div class="section-head"><h2>Доступно за АМ</h2><button class="link" data-action="all-rewards">Все →</button></div><div class="grid">${list.map(rewardCard).join('')}</div><div class="section-head"><h2>Активности</h2><button class="link" data-view="promotions">Смотреть →</button></div><div class="notice">Лайки, комментарии, подписки и события начисляют АМ только один раз по правилам клуба.</div>`}
function rewardCard(r){const reasons=eligibility(r),locked=reasons.length>0; if(locked&&!r.lockedVisible)return ''; return `<button class="reward card ${locked?'locked':''}" data-reward="${r.id}"><div class="reward-visual">${r.emoji||'🎁'}</div><div class="reward-body"><h3>${esc(r.title)}</h3><div class="price">${am(r.price)}</div><span class="tag">${r.stock} шт.</span>${r.minDiscount?`<span class="tag">скидка ≥${r.minDiscount}%</span>`:''}${r.birthday?`<span class="tag">день рождения</span>`:''}${r.gender!=='any'?`<span class="tag">${r.gender==='male'?'мужчинам':'женщинам'}</span>`:''}${locked?`<div class="sub" style="color:#bd5260">${esc(reasons[0])}</div>`:''}</div></button>`}
function promotions(){const ks=['Все','Постоянные','Сезонные','События'], arr=state.promotions.filter(p=>promoFilter==='Все'||p.kind===promoFilter);return `${head('Акции','Получайте дополнительные АМ')}<div class="filters">${ks.map(k=>`<button data-pfilter="${k}" class="${promoFilter===k?'active':''}">${k}</button>`).join('')}</div><div class="list">${arr.map(p=>`<button class="rowcard card" data-promo="${p.id}"><div><h3>${esc(p.title)}</h3><p>${esc(p.text)} · ${esc(p.kind)}</p></div><span class="pill">${esc(p.reward)}</span></button>`).join('')}</div>`}
function orders(){const arr=state.orders.filter(o=>o.customer===current().id);return `${head('Заказы','История приходит из CRM')}<div class="notice">Ручной ввод заказов отключён. После подключения CRM здесь автоматически появятся реальные заказы.</div><div class="list">${arr.length?arr.map(o=>`<button class="rowcard card" data-order="${o.id}"><div><h3>Заказ ${esc(o.number)}</h3><p>${o.date} · ${esc(o.title)} · ${esc(o.status)}</p><div class="order-money">${money(o.paid)}</div></div><span class="pill">+${o.earned} АМ</span></button>`).join(''):'<div class="card empty">Заказов пока нет</div>'}</div>`}
function history(){const arr=state.ledger.filter(x=>x.customer===current().id);return `${head('История','Все движения кошелька АМ')}<div class="list">${arr.map(x=>`<button class="rowcard card" data-ledger="${x.id}"><div><h3>${esc(x.reason)}</h3><p>${esc(x.type)} · ${x.date} · баланс после ${x.balance} АМ</p></div><b class="${x.amount>=0?'plus':'minus'}">${x.amount>=0?'+':''}${x.amount} АМ</b></button>`).join('')}</div>`}
function profile(){const c=current();return `${head('Профиль','Данные участника клуба')}<section class="profile-id card"><h2>${esc(c.name)}</h2><div class="data"><div class="cell"><span>Телефон</span><b>${c.phone}</b></div><div class="cell"><span>CRM №</span><b>${c.crm}</b></div><div class="cell"><span>Дата рождения</span><b>${c.birth||'—'}</b></div><div class="cell"><span>Пол</span><b>${c.gender==='male'?'Мужчина':c.gender==='female'?'Женщина':'Не указан'}</b></div><div class="cell"><span>Скидка</span><b>${c.discount}%</b></div><div class="cell"><span>Баланс</span><b>${c.balance} АМ</b></div></div></section><div class="section-head"><h2>Каналы</h2></div><div class="channels">${state.channels.map(ch=>`<div class="channel card"><div class="mark">${esc(ch.type.slice(0,2).toUpperCase())}</div><div><b>${esc(ch.name)}</b><div class="sub">${esc(ch.link)} · бонус ${ch.bonus} АМ</div></div><span class="pill ${ch.active?'status-on':'status-off'}">${ch.active?'Подключён':'Неактивен'}</span></div>`).join('')}</div><div class="section-head"><h2>Настройки</h2></div><div class="list"><button class="rowcard card" data-action="edit-profile"><div><h3>Личные данные</h3><p>Изменить дату рождения и пол в тестовом профиле</p></div><span>›</span></button><button class="rowcard card" data-action="reset"><div><h3>Сбросить тестовые данные</h3><p>Вернуть исходное состояние Stage 10.1</p></div><span>↻</span></button></div>`}
function client(){const body={home,promotions,orders,history,profile}[view]();return `<main class="shell screen">${body}</main>${nav()}`}
const adminTabs=[['customers','Клиенты'],['orders','Заказы'],['operations','Операции'],['promotions','Акции'],['events','События'],['gifts','Подарки'],['rewards','Каталог'],['channels','Каналы']];
function adminHead(){return `${head('АМ Клуб — админка','Stage 10.1 • тестовые данные')}<div class="admin-tabs">${adminTabs.map(([id,t])=>`<button data-atab="${id}" class="${adminTab===id?'active':''}">${t}</button>`).join('')}</div>`}
function adminCustomers(){const c=state.customers.find(x=>x.id===selectedCustomer)||state.customers[0]; const ord=state.orders.filter(o=>o.customer===c.id), led=state.ledger.filter(l=>l.customer===c.id).slice(0,5);return `<input class="search" id="customerSearch" placeholder="Телефон, имя или CRM №"><div class="admin-layout"><div class="list" id="customerList">${state.customers.map(x=>customerRow(x,c.id)).join('')}</div><section class="detail card"><div class="entity-head"><div><div class="sub">Клиент CRM ${c.crm}</div><h2>${esc(c.name)}</h2><div class="sub">${c.phone} · ${c.birth||'дата рождения не указана'}</div></div><span class="pill">скидка ${c.discount}%</span></div><div class="metrics"><div class="metric"><span>Баланс</span><b>${c.balance} АМ</b></div><div class="metric"><span>Оборот</span><b>${money(c.turnover)}</b></div><div class="metric"><span>Остаток ₽</span><b>${c.remainder}</b></div><div class="metric"><span>Заказов</span><b>${ord.length}</b></div></div><div class="actions"><button class="btn primary" data-adjust="plus">+ Начислить АМ</button><button class="btn danger" data-adjust="minus">− Списать АМ</button></div><div class="section-head"><h2>Заказы</h2></div><div class="list">${ord.length?ord.map(o=>`<button class="rowcard card" data-order="${o.id}"><div><h3>${o.number}</h3><p>${o.date} · ${esc(o.title)}</p></div><b>${money(o.paid)}</b></button>`).join(''):'<div class="empty">Заказов нет</div>'}</div><div class="section-head"><h2>Последние АМ</h2></div><div class="list">${led.map(l=>`<div class="rowcard card"><div><h3>${esc(l.reason)}</h3><p>${l.date}</p></div><b class="${l.amount>=0?'plus':'minus'}">${l.amount>=0?'+':''}${l.amount}</b></div>`).join('')}</div></section></div>`}
