/* AM Club Stage 10.1.3 overrides */
const AMP_CONTACTS={address:'Гоголя, 2',phone:'2820580',phoneHref:'tel:+78312820580',site:'amplituda-nn.ru',siteHref:'https://amplituda-nn.ru/',email:'2820580@mail.ru'};
const AMP_PROMO_LINKS={p1:'https://vk.com/amplitudann',p2:'https://t.me/AmplitudAm',p3:'https://max.ru/amplituda',p4:'https://amplituda-nn.ru/',p5:'https://amplituda-nn.ru/'};
const AMP_EVENT_LINKS={e1:'https://amplituda-nn.ru/',e2:'https://amplituda-nn.ru/'};
const ampHref=v=>{let s=String(v||'').trim();if(!s)return '';if(/^(https?:|mailto:|tel:)/i.test(s))return s;return 'https://'+s.replace(/^\/+/, '')};
const ampMapHref='https://yandex.ru/maps/?text='+encodeURIComponent('Нижний Новгород, Гоголя, 2');
const ampSupportHref=()=>`mailto:${AMP_CONTACTS.email}?subject=${encodeURIComponent('АМ Клуб — поддержка')}&body=${encodeURIComponent('Клиент: '+current().name+'\nТелефон: '+current().phone+'\nCRM №: '+current().crm+'\n\nОпишите вопрос:')}`;
state.promotions.forEach(p=>{if(!p.link)p.link=AMP_PROMO_LINKS[p.id]||''});
state.events.forEach(e=>{if(!e.link)e.link=AMP_EVENT_LINKS[e.id]||''});
save();

head=function(title,sub,withAdmin=true){return `<header class="top"><div class="brand"><div class="logo"><img src="./amp-logo.svg?v=10.1.3" alt="Амплитуда"></div><div><h1 class="title">${title}</h1><div class="sub">${sub||''}</div></div></div>${withAdmin?`<button class="admin-switch" data-action="toggle-admin">${admin?'Клиент':'Админка'}</button>`:''}</header>`};
function ampContactsBlock(){return `<section class="contact-card card"><div class="section-head compact"><div><h2>Амплитуда</h2><div class="sub">Контакты типографии</div></div></div><div class="contact-links"><a href="${ampMapHref}" target="_blank" rel="noopener"><b>Адрес</b><span>${AMP_CONTACTS.address}</span></a><a href="${AMP_CONTACTS.phoneHref}"><b>Телефон</b><span>${AMP_CONTACTS.phone}</span></a><a href="${AMP_CONTACTS.siteHref}" target="_blank" rel="noopener"><b>Сайт</b><span>${AMP_CONTACTS.site}</span></a><a href="mailto:${AMP_CONTACTS.email}"><b>Почта</b><span>${AMP_CONTACTS.email}</span></a></div></section>`}
const ampBaseHome=home;
home=function(){return ampBaseHome()+ampContactsBlock()};

promotions=function(){const ks=['Все','Постоянные','Сезонные','События'],arr=state.promotions.filter(p=>(p.active!==false)&&(promoFilter==='Все'||p.kind===promoFilter));return `${head('Акции','Получайте дополнительные АМ')}<div class="filters">${ks.map(k=>`<button data-pfilter="${k}" class="${promoFilter===k?'active':''}">${k}</button>`).join('')}</div><div class="list">${arr.map(p=>{const href=ampHref(p.link),body=`<div><h3>${esc(p.title)}</h3><p>${esc(p.text||'')}</p></div><span class="pill">${esc(promoRewardLabel(p))} ↗</span>`;return href?`<a class="rowcard card linkcard" href="${esc(href)}" target="_blank" rel="noopener">${body}</a>`:`<div class="rowcard card">${body}</div>`}).join('')}</div>`};

profile=function(){const c=current();return `${head('Профиль','Данные участника клуба')}<section class="profile-id card"><h2>${esc(c.name)}</h2><div class="data"><div class="cell"><span>Телефон</span><b>${c.phone}</b></div><div class="cell"><span>CRM №</span><b>${c.crm}</b></div><div class="cell"><span>Дата рождения</span><b>${c.birth||'—'}</b></div><div class="cell"><span>Пол</span><b>${c.gender==='male'?'Мужской':c.gender==='female'?'Женский':'Не указан'}</b></div><div class="cell"><span>Скидка</span><b>${c.discount}%</b></div><div class="cell"><span>Баланс</span><b>${c.balance} АМ</b></div></div></section><div class="section-head"><h2>Каналы</h2></div><div class="channels">${state.channels.map(ch=>`<a class="channel card channel-link" href="${esc(ampHref(ch.link))}" target="_blank" rel="noopener"><div class="mark">${esc(ch.type.slice(0,2).toUpperCase())}</div><div><b>${esc(ch.name)}</b><div class="sub">${esc(ch.link)} · бонус ${ch.bonus} АМ</div></div><span class="pill ${ch.active?'status-on':'status-off'}">${ch.active?'Подключён':'Неактивен'} ↗</span></a>`).join('')}</div><div class="section-head"><h2>Настройки</h2></div><div class="list"><button class="rowcard card" data-action="edit-profile"><div><h3>Личные данные</h3><p>Изменить дату рождения и пол</p></div><span>›</span></button><a class="rowcard card linkcard" href="${ampSupportHref()}"><div><h3>Написать в поддержку</h3><p>Письмо на ${AMP_CONTACTS.email}</p></div><span>✉</span></a><button class="rowcard card" data-action="test-login"><div><h3>Тестовый вход / QR</h3><p>Проверка вместо SMS до подключения провайдера</p></div><span>⌁</span></button><button class="rowcard card" data-action="reset"><div><h3>Сбросить тестовые данные</h3><p>Вернуть исходное состояние Stage 10.1</p></div><span>↻</span></button></div>${ampContactsBlock()}`};

adminPromotions=function(){return `<div class="section-head"><div><h2>Акции</h2><div class="sub">Начисления, лимиты, время, условия и ссылка перехода</div></div><button class="btn primary" data-action="new-promo">+ Акция</button></div><div class="grid">${state.promotions.map(p=>{const href=ampHref(p.link);return `<div class="entity card"><div class="entity-head"><h3>${esc(p.title)}</h3><span class="pill">${p.active===false?'Выключена':esc(promoRewardLabel(p))}</span></div><p>${esc(p.text||'')}</p><div class="media-row">${p.from||p.to?`<span class="media-chip">${esc(promoPeriod(p))}</span>`:''}${p.minDiscount?`<span class="media-chip">скидка ≥${p.minDiscount}%</span>`:''}${p.gender&&p.gender!=='any'?`<span class="media-chip">${p.gender==='male'?'мужской':'женский'}</span>`:''}${p.birthday?'<span class="media-chip">день рождения</span>':''}</div><div class="entity-actions">${href?`<a class="btn secondary external-link" href="${esc(href)}" target="_blank" rel="noopener">Перейти ↗</a>`:''}<button class="btn secondary" data-edit-promo="${p.id}">Редактировать</button></div></div>`}).join('')}</div>`};
adminEvents=function(){return `<div class="section-head"><h2>События</h2><button class="btn primary" data-action="new-event">+ Событие</button></div><div class="list">${state.events.map(e=>{const href=ampHref(e.link);return `<div class="entity card"><div class="entity-head"><h3>${esc(e.title)}</h3><span class="pill">${e.active?'Активно':'Выключено'}</span></div><p>Триггер: ${esc(e.trigger)} · действие: ${esc(e.action)}</p><div class="entity-actions">${href?`<a class="btn secondary external-link" href="${esc(href)}" target="_blank" rel="noopener">Перейти ↗</a>`:''}<button class="btn secondary" data-action="test-event" data-id="${e.id}">Тест</button><button class="btn secondary" data-edit-event="${e.id}">Редактировать</button></div></div>`}).join('')}</div>`};
adminChannels=function(){return `<div class="section-head"><h2>Каналы</h2><button class="btn primary" data-action="new-channel">+ Канал</button></div><div class="notice">Можно добавлять любое количество площадок и отдельных групп одного типа.</div><div class="list">${state.channels.map(ch=>`<div class="rowcard card"><div><h3>${esc(ch.name)}</h3><p>${esc(ch.type)} · <a class="inline-link" href="${esc(ampHref(ch.link))}" target="_blank" rel="noopener">${esc(ch.link)} ↗</a> · бонус ${ch.bonus} АМ</p></div><button class="btn secondary" data-edit-channel="${ch.id}">Изменить</button></div>`).join('')}</div>`};

function ampPostProcessModal(){const m=document.querySelector('.modal');if(!m)return;['#rGender','#promoGender','#pGender'].forEach(sel=>{const x=m.querySelector(sel);if(!x)return;[...x.options].forEach(o=>{if(o.value==='male')o.textContent='Мужской';if(o.value==='female')o.textContent='Женский'})})}
function ampInjectPromoLink(){const m=document.querySelector('.modal');if(!m||m.querySelector('#promoLink')||!m.querySelector('#promoId'))return;const point=m.querySelector('#promoMain')?.closest('.field')||m.querySelector('.modal-actions');const wrap=document.createElement('label');wrap.className='field';wrap.innerHTML='<span>Ссылка перехода</span><input id="promoLink" placeholder="https://...">';const p=state.promotions.find(x=>x.id===m.querySelector('#promoId').value);wrap.querySelector('input').value=p?.link||'';point.before(wrap)}
function ampInjectEventLink(){const m=document.querySelector('.modal');if(!m||m.querySelector('#eventLink')||m.querySelector('#simpleType')?.value!=='event')return;const wrap=document.createElement('label');wrap.className='field';wrap.innerHTML='<span>Ссылка перехода</span><input id="eventLink" placeholder="https://...">';const e=state.events.find(x=>x.id===m.querySelector('#simpleId')?.value);wrap.querySelector('input').value=e?.link||'';m.querySelector('.modal-actions').before(wrap)}

document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const a=b.dataset.action;if(b.dataset.editReward||b.dataset.editPromo||b.dataset.editEvent||a==='new-reward'||a==='new-promo'||a==='new-event'||a==='edit-profile')setTimeout(()=>{ampPostProcessModal();ampInjectPromoLink();ampInjectEventLink()},0)},false);

render();
