document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
 if(b.dataset.view){view=b.dataset.view;render();return} if(b.dataset.atab){adminTab=b.dataset.atab;render();return}
 if(b.dataset.customer){selectedCustomer=b.dataset.customer;render();return} if(b.dataset.reward){rewardModal(state.rewards.find(x=>x.id===b.dataset.reward));return}
 if(b.dataset.promo){promotionModal(state.promotions.find(x=>x.id===b.dataset.promo));return} if(b.dataset.order){orderModal(state.orders.find(x=>x.id===b.dataset.order));return} if(b.dataset.adjust){adjustment(b.dataset.adjust==='plus'?1:-1);return}
 if(b.dataset.editReward){rewardEditor(state.rewards.find(x=>x.id===b.dataset.editReward));return} if(b.dataset.editPromo){promotionEditor(state.promotions.find(x=>x.id===b.dataset.editPromo));return}
 if(b.dataset.editEvent){simpleEditor('event',state.events.find(x=>x.id===b.dataset.editEvent));return} if(b.dataset.editChannel){simpleEditor('channel',state.channels.find(x=>x.id===b.dataset.editChannel));return}
 if(b.dataset.pfilter){promoFilter=b.dataset.pfilter;render();return}
 if(b.dataset.redeem){const r=state.rewards.find(x=>x.id===b.dataset.redeem),c=current(),reasons=eligibility(r);if(reasons.length){toast(reasons[0]);return}c.balance-=r.price;state.customer.balance=c.balance;r.stock--;state.redemptions.unshift({id:'red'+Date.now(),reward:r.id,customer:c.id,price:r.price,status:'Оформлено',date:'14.09.2026'});state.ledger.unshift({id:'l'+Date.now(),customer:c.id,date:'14.09.2026 14:50',type:'За АМ',reason:r.title,amount:-r.price,balance:c.balance});save();closeModal();toast('Оформлено. АМ списаны');render();return}
 const a=b.dataset.action;if(!a)return;
 if(a==='toggle-admin'){admin=!admin;render()} else if(a==='close')closeModal(); else if(a==='all-rewards'){admin=false;view='home';render();toast('Все доступные позиции показаны ниже')}
 else if(a==='new-reward')rewardEditor(); else if(a==='new-promo')promotionEditor(); else if(a==='new-event')simpleEditor('event'); else if(a==='new-gift')simpleEditor('gift'); else if(a==='new-channel')simpleEditor('channel'); else if(a==='edit-profile')profileEditor();
 else if(a==='save-adjust'){const amount=Math.max(1,Number($('#adjAmount').value||0)),reason=$('#adjReason').value.trim(),sign=Number(b.dataset.sign);if(!reason){toast('Укажи причину');return}const c=state.customers.find(x=>x.id===selectedCustomer);if(sign<0&&amount>c.balance){toast('Недостаточно АМ');return}c.balance+=sign*amount;if(c.id===state.customer.id)state.customer.balance=c.balance;state.ledger.unshift({id:'l'+Date.now(),customer:c.id,date:'14.09.2026 14:50',type:'Корректировка',reason,amount:sign*amount,balance:c.balance});save();closeModal();render();toast('Операция записана в ledger')}
 else if(a==='save-reward'){const id=$('#rewardId').value;const obj={id,title:$('#rTitle').value.trim(),category:$('#rCategory').value.trim(),desc:$('#rDesc').value.trim(),price:Number($('#rPrice').value||0),stock:Number($('#rStock').value||0),limit:Number($('#rLimit').value||0),sort:Number($('#rSort').value||0),fulfill:$('#rFulfill').value.trim(),emoji:$('#rEmoji').value.trim()||'🎁',main:$('#rMain').value.trim(),media:$('#rMedia').value.split('\n').map(x=>x.trim()).filter(Boolean),minDiscount:Number($('#rDiscount').value||0),gender:$('#rGender').value,birthday:$('#rBirthday').checked,from:$('#rFrom').value,to:$('#rTo').value,lockedVisible:$('#rLockedVisible').checked,active:$('#rActive').checked};if(!obj.title){toast('Нужно название');return}const i=state.rewards.findIndex(x=>x.id===id);if(i>=0)state.rewards[i]=obj;else state.rewards.push(obj);save();closeModal();render();toast('Позиция сохранена')}
 else if(a==='save-promo'){const id=$('#promoId').value;const obj={id,title:$('#promoTitle').value.trim(),text:$('#promoText').value.trim(),kind:$('#promoKind').value,rewardType:$('#promoRewardType').value,amount:Number($('#promoAmount').value||0),maxPerAccrual:Number($('#promoMax').value||0),limitPerClient:Number($('#promoLimitClient').value||0),totalLimit:Number($('#promoTotalLimit').value||0),from:$('#promoFrom').value,to:$('#promoTo').value,main:$('#promoMain').value.trim(),media:$('#promoMedia').value.split('\n').map(x=>x.trim()).filter(Boolean),minDiscount:Number($('#promoDiscount').value||0),gender:$('#promoGender').value,birthday:$('#promoBirthday').checked,active:$('#promoActive').checked};if(!obj.title){toast('Нужно название акции');return}if(obj.amount<0){toast('Начисление не может быть отрицательным');return}upsert(state.promotions,obj);save();closeModal();render();toast('Акция сохранена')}
 else if(a==='save-profile'){const c=current();c.birth=$('#pBirth').value;c.gender=$('#pGender').value;state.customer.birth=c.birth;state.customer.gender=c.gender;save();closeModal();render();toast('Профиль обновлён')}
 else if(a==='save-simple'){const type=$('#simpleType').value,id=$('#simpleId').value||type+Date.now(),A=$('#simpleA').value.trim(),B=$('#simpleB').value.trim();if(!A){toast('Заполни название');return}if(type==='event'){const o={id,title:A,trigger:'custom',action:B,active:true};upsert(state.events,o)}if(type==='gift'){state.gifts.push({id,title:A,audience:B,status:'Активен'})}if(type==='channel'){const o={id,name:A,link:B,type:$('#simpleC').value.trim(),bonus:Number($('#simpleD').value||0),active:true,primary:false};upsert(state.channels,o)}save();closeModal();render();toast('Сохранено')}
 else if(a==='test-event'){const ev=state.events.find(x=>x.id===b.dataset.id);const c=current();if(ev?.action.includes('+300')){c.balance+=300;state.customer.balance=c.balance;state.ledger.unshift({id:'l'+Date.now(),customer:c.id,date:'14.09.2026 14:50',type:'Событие',reason:ev.title,amount:300,balance:c.balance});save();render();toast('+300 АМ начислено')}else toast('Тест события выполнен')}
 else if(a==='issue-gift')toast('Тестовая выдача подарка создана'); else if(a==='reset'){localStorage.removeItem('ampclub.stage10.1');state=JSON.parse(JSON.stringify(seed));save();render();toast('Тестовые данные сброшены')}
});
function upsert(arr,obj){const i=arr.findIndex(x=>x.id===obj.id);if(i>=0)arr[i]=obj;else arr.push(obj)}
window.__AMP_PYTHON__={backend:'python',stage:'10.1',ordersSource:'crm_connector'};
render();
