/* AM Club legal UI v1.0 — staging. Production receipts must be stored server-side. */
const AMP_LEGAL_VERSION='1.0-2026-09-15';
const AMP_LEGAL_DRAFT_KEY='ampclub.legal.draft.v1';
const AMP_LEGAL_RECEIPT_KEY='ampclub.legal.receipt.v1';
const legalRead=(key,def={})=>{try{return JSON.parse(localStorage.getItem(key))||def}catch(e){return def}};
const legalDraftRead=()=>{try{return JSON.parse(sessionStorage.getItem(AMP_LEGAL_DRAFT_KEY))||{}}catch(e){return {}}};
const legalDraftSave=v=>sessionStorage.setItem(AMP_LEGAL_DRAFT_KEY,JSON.stringify(v));
const legalReceiptSave=v=>localStorage.setItem(AMP_LEGAL_RECEIPT_KEY,JSON.stringify(v));
const legalEsc=v=>typeof esc==='function'?esc(v):String(v||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function ampLegalConsentBlock(){const d=legalDraftRead();return `<div class="legal-consents" id="ampLegalConsents"><label class="legal-consent-row"><input type="checkbox" id="legalAge" ${d.age?'checked':''}><span>Мне исполнилось <b>18 лет</b>.</span></label><label class="legal-consent-row"><input type="checkbox" id="legalRules" ${d.rules?'checked':''}><span>Я принимаю <a href="./legal/rules.html" target="_blank" rel="noopener">Правила АМ Клуба</a> версии 1.0.</span></label><label class="legal-consent-row"><input type="checkbox" id="legalPd" ${d.pd?'checked':''}><span>Я отдельно даю <a href="./legal/personal-data-consent.html" target="_blank" rel="noopener">Согласие на обработку персональных данных</a> и ознакомлен(а) с <a href="./legal/privacy.html" target="_blank" rel="noopener">Политикой обработки ПД</a>.</span></label><label class="legal-consent-row optional"><input type="checkbox" id="legalMarketing" ${d.marketing?'checked':''}><span><b>Необязательно:</b> согласен(на) получать <a href="./legal/marketing-consent.html" target="_blank" rel="noopener">рекламные и маркетинговые сообщения</a>. Можно отказаться в любой момент без выхода из АМ Клуба.</span></label><div class="legal-note">Продолжая регистрацию, вы не соглашаетесь на рекламу автоматически. Обязательны только возраст 18+, Правила и отдельное согласие на ПД.</div></div>`}
function ampLegalDecorateRegistration(){const phone=document.querySelector('#regPhone');if(!phone||document.querySelector('#ampLegalConsents'))return;const btn=document.querySelector('[data-auth="send-register-code"]');if(!btn)return;btn.insertAdjacentHTML('beforebegin',ampLegalConsentBlock())}
function ampLegalProfileBlock(){const r=legalRead(AMP_LEGAL_RECEIPT_KEY,{});const marketing=!!r.marketing;const pd=r.pd?`Принято · версия ${legalEsc(r.version||'1.0')}`:'Нет серверной фиксации в тестовой версии';return `<section class="legal-profile card"><div class="section-head compact"><div><h2>Документы и согласия</h2><div class="sub">Единые для приложения и веб-версии</div></div></div><div class="legal-status"><span>Согласие на обработку ПД</span><b>${pd}</b></div><div class="legal-status"><span>Рекламные сообщения</span><div><b>${marketing?'Разрешены':'Не разрешены'}</b> <button class="legal-small-btn" data-legal="${marketing?'marketing-off':'marketing-on'}">${marketing?'Отключить':'Разрешить'}</button></div></div><div class="legal-links-grid"><a href="./legal/privacy.html">Политика ПД</a><a href="./legal/personal-data-consent.html">Согласие на ПД</a><a href="./legal/marketing-consent.html">Реклама</a><a href="./legal/rules.html">Правила АМ Клуба</a><a href="./legal/cookies.html">Cookie и устройство</a><a href="./legal/withdrawal.html">Отзыв и обращения</a></div><div class="legal-note">В production согласия хранятся на сервере: клиент, версия документа, дата/время, канал, технические данные сессии и история отзыва. localStorage здесь используется только для текущего стенда.</div></section>`}
try{const prevProfileLegal=profile;profile=function(){return prevProfileLegal()+ampLegalProfileBlock()}}catch(e){}
try{const prevRenderLegal=render;render=function(){prevRenderLegal();setTimeout(ampLegalDecorateRegistration,0)}}catch(e){}
document.addEventListener('change',e=>{if(!e.target.closest('#ampLegalConsents'))return;legalDraftSave({age:!!document.querySelector('#legalAge')?.checked,rules:!!document.querySelector('#legalRules')?.checked,pd:!!document.querySelector('#legalPd')?.checked,marketing:!!document.querySelector('#legalMarketing')?.checked,version:AMP_LEGAL_VERSION})});
document.addEventListener('click',e=>{const send=e.target.closest('[data-auth="send-register-code"]');if(send){const age=!!document.querySelector('#legalAge')?.checked,rules=!!document.querySelector('#legalRules')?.checked,pd=!!document.querySelector('#legalPd')?.checked,marketing=!!document.querySelector('#legalMarketing')?.checked;if(!age||!rules||!pd){e.preventDefault();e.stopImmediatePropagation();if(typeof toast==='function')toast(!age?'Подтвердите, что вам исполнилось 18 лет':!rules?'Примите Правила АМ Клуба':'Дайте отдельное согласие на обработку персональных данных');return}legalDraftSave({age,rules,pd,marketing,version:AMP_LEGAL_VERSION,acceptedAt:new Date().toISOString()})}},true);
document.addEventListener('click',e=>{const savePin=e.target.closest('[data-auth="save-pin"]');if(!savePin)return;const d=legalDraftRead();setTimeout(()=>{try{if(typeof ampAuth!=='undefined'&&ampAuth.registered){legalReceiptSave({version:AMP_LEGAL_VERSION,age:!!d.age,rules:!!d.rules,pd:!!d.pd,marketing:!!d.marketing,pdAcceptedAt:d.acceptedAt||new Date().toISOString(),marketingAcceptedAt:d.marketing?(d.acceptedAt||new Date().toISOString()):null,marketingRevokedAt:null,source:'staging-browser-only',phone:ampAuth.phone||''});sessionStorage.removeItem(AMP_LEGAL_DRAFT_KEY);render()}}catch(err){}},50)},true);
document.addEventListener('click',e=>{const b=e.target.closest('[data-legal]');if(!b)return;e.preventDefault();const r=legalRead(AMP_LEGAL_RECEIPT_KEY,{version:AMP_LEGAL_VERSION});if(b.dataset.legal==='marketing-off'){r.marketing=false;r.marketingRevokedAt=new Date().toISOString();legalReceiptSave(r);if(typeof toast==='function')toast('Рекламные сообщения отключены');render()}else if(b.dataset.legal==='marketing-on'){r.marketing=true;r.marketingAcceptedAt=new Date().toISOString();r.marketingRevokedAt=null;legalReceiptSave(r);if(typeof toast==='function')toast('Согласие на рекламные сообщения включено');render()}},true);
setTimeout(()=>{try{render()}catch(e){ampLegalDecorateRegistration()}},0);
