/* persist links + test auth */
let ampPendingPromoLink='',ampPendingPromoId='',ampPendingEventLink='',ampPendingEventId='';
document.addEventListener('input',e=>{if(e.target.id==='promoLink')ampPendingPromoLink=e.target.value;if(e.target.id==='eventLink')ampPendingEventLink=e.target.value});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const a=b.dataset.action;if(b.dataset.editPromo||a==='new-promo')setTimeout(()=>{const id=document.querySelector('#promoId')?.value;if(id){ampPendingPromoId=id;ampPendingPromoLink=document.querySelector('#promoLink')?.value||''}},0);if(b.dataset.editEvent||a==='new-event')setTimeout(()=>{const id=document.querySelector('#simpleId')?.value;if(id){ampPendingEventId=id;ampPendingEventLink=document.querySelector('#eventLink')?.value||''}},0);if(a==='save-promo')setTimeout(()=>{const p=state.promotions.find(x=>x.id===ampPendingPromoId);if(p){p.link=ampPendingPromoLink.trim();save();render()}},0);if(a==='save-simple'&&ampPendingEventId)setTimeout(()=>{const x=state.events.find(v=>v.id===ampPendingEventId);if(x){x.link=ampPendingEventLink.trim();save();render()}ampPendingEventId=''},0)});
const ampAuthKey='ampclub.testVerified';
const ampQrParam=new URLSearchParams(location.search).get('testqr');
if(ampQrParam==='1'){localStorage.setItem(ampAuthKey,'1');history.replaceState({},'',location.pathname+location.hash)}
const ampProfileBaseQr=profile;
profile=function(){const verified=localStorage.getItem(ampAuthKey)==='1';const qr='https://quickchart.io/qr?size=220&margin=1&text='+encodeURIComponent(location.origin+location.pathname+'?testqr=1');return ampProfileBaseQr().replace(/<button class="rowcard card" data-action="test-login">[\s\S]*?<\/button>/,`<section class="login-card card"><img class="login-qr" src="${qr}" alt="QR"><div><h3>QR-код для входа</h3><p>Тестовый режим вместо SMS. Отсканируй QR или введи контрольный код <b>1111</b>.</p><div class="test-auth-row"><input id="ampTestCode" inputmode="numeric" maxlength="4" placeholder="Код"><button class="btn primary" data-action="verify-test-code">Проверить</button></div><div class="sub auth-state">${verified?'✓ Тестовый вход подтверждён':'Вход пока не подтверждён'}</div></div></section>`)};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.dataset.action!=='verify-test-code')return;const code=document.querySelector('#ampTestCode')?.value.trim();if(code==='1111'){localStorage.setItem(ampAuthKey,'1');render();toast('Тестовый вход подтверждён')}else toast('Неверный тестовый код')});
render();
